name = "WignerSeitz"
uuid = "febcb537-6ed7-48c5-819e-90cfcb7df844"
authors = ["Brandon Flores <bsflores@wisc.edu>"]
version = "0.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NormalForms = "109d20d8-9763-411c-9b60-7eb2a068657f"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
